spring:
  application:
    name: easydb
  metrics:
    prometheus:
      enabled: true

management:
  security:
    enabled: false

  metrics:
    distribution:
      percentiles:
        "[spaceUnlockingTime]": 0.95, 0.99
        "[spaceLockingTime]": 0.95, 0.99
        "[bucketUnlockingTime]": 0.95, 0.99
        "[bucketLockingTime]": 0.95, 0.99
        "[elementUnlockingTime]": 0.95, 0.99
        "[elementLockingTime]": 0.95, 0.99
        "[compoundTransactionTime]": 0.95, 0.99
        "[singleElementTransactionTime]": 0.95, 0.99

  endpoints:
    web:
      exposure:
        include: '*'

mongo:
  databaseName: easydb
  hosts: "localhost:27017"
  username: easydb
  password: 123456
  adminDatabaseName: admin
  adminUsername: admin
  adminPassword: 123456

server:
  max-http-header-size: 65536

