spring:
  application:
    name: easydb
  metrics:
    prometheus:
      enabled: true

management:
  security:
    enabled: false

  endpoints:
    web:
      exposure:
        include: '*'

mongo:
  databaseName: easydb
  hosts: "localhost:27017"
  username: easydb
  password: 123456
  adminDatabaseName: admin
  adminUsername: admin
  adminPassword: 123456
server:
  max-http-header-size: 65536
