space:
  spaceName:
    testSpace

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  application:
    name: bookstore
  metrics:
    prometheus:
      enabled: true

management:
  security:
    enabled: false

  endpoints:
    web:
      exposure:
        include: '*'