zookeeper:
  connectionString: "localhost:2181"

mongo:
  databaseName: easydb
  hosts: "localhost:27017"
  username: easydb
  password: 123456
  adminDatabaseName: admin
  adminUsername: admin
  adminPassword: 123456