spring:
  application:
    name: easydb
  metrics:
    prometheus:
      enabled: true

management:
  security:
    enabled: false

  endpoints:
    web:
      exposure:
        include: '*'

mongo:
  databaseName: easydb
  hosts: "mongo-router1:27017,mongo-router2:27017"
  username: easydb
  password: 123456
  adminDatabaseName: admin
  adminUsername: admin
  adminPassword: 123456

zookeeper:
  connectionString: "zookeeper:2181"