{
 "title": "easydb",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server 5xx RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_v1_requests_5xx_total[1m]))"
    }
   ]
  },
  {
   "title": "Server 4xx RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_v1_requests_4xx_total[1m]))"
    }
   ]
  },
  {
   "title": "Server 2xx RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_v1_requests_2xx_total[1m]))"
    }
   ]
  },
  {
   "title": "Server RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_v1_requests_all_total[1m]))"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Threads alive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_live" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "JVM memory used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}"
    }
   ]
  },
  {
   "title": "CPU count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_count" }
   ]
  },
  { "title": "Locker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Lock element RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(lockElement_total[1m]))"
    }
   ]
  },
  {
   "title": "Unlock element RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(unlockElement_total[1m]))"
    }
   ]
  },
  {
   "title": "Lock bucket RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(lockBucket_total[1m]))"
    }
   ]
  },
  {
   "title": "Unlock bucket RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(unlockBucket_total[1m]))"
    }
   ]
  },
  {
   "title": "Lock space RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(lockSpace_total[1m]))"
    }
   ]
  },
  {
   "title": "Unlock space RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(unlockSpace_total[1m]))"
    }
   ]
  },
  {
   "title": "Element locker errors RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(elementLockerErrors_total[1m]))"
    }
   ]
  },
  {
   "title": "Bucket locker errors RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(bucketLockerErrors_total[1m]))"
    }
   ]
  },
  {
   "title": "Space locker errors RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(spaceLockerErrors_total[1m]))"
    }
   ]
  },
  {
   "title": "Element locker Timeouts RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(elementLockerTimeouts_total[1m]))"
    }
   ]
  },
  {
   "title": "Bucket locker Timeouts RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(bucketLockerTimeouts_total[1m]))"
    }
   ]
  },
  {
   "title": "Space locker Timeouts RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(spaceLockerTimeouts_total[1m]))"
    }
   ]
  },
  {
   "title": "Element locking time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(elementLockingTime_seconds_max[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Element unlocking time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(elementUnlockingTime_seconds_max[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Bucket locking time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(bucketLockingTime_seconds_max[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Bucket unlocking time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(bucketUnlockingTime_seconds_max[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Space locking time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(spaceLockingTime_seconds_max[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Space unlocking time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(spaceUnlockingTime_seconds_max[1m])) by (instance)"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Begin transaction RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_beginTransaction_total[1m]))"
    }
   ]
  },
  {
   "title": "Commit transaction RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_commitTransaction_total[1m]))"
    }
   ]
  },
  {
   "title": "Add transaction operation RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(api_addTransactionOperation_total[1m])) by (instance, operation)"
    }
   ]
  },
  {
   "title": "Aborted transactions RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(abortedTransactions_total[1m]))"
    }
   ]
  },
  {
   "title": "Compound transaction time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(compoundTransactionTime_seconds_max[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Single element transaction time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(singleElementTransactionTime_seconds_max[1m])) by (instance)"
    }
   ]
  },
  { "title": "Bucket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 } },
  {
   "title": "Delete Bucket RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_deleteBucket_total[1m]))"
    }
   ]
  },
  {
   "title": "Add Element RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 149 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_addElement_total[1m]))"
    }
   ]
  },
  {
   "title": "Update Element RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_updateElement_total[1m]))"
    }
   ]
  },
  {
   "title": "Get Element RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_getElement_total[1m]))"
    }
   ]
  },
  {
   "title": "Delete Element RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_deleteElement_total[1m]))"
    }
   ]
  },
  {
   "title": "Filter Elements RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_filterElements_total[1m]))"
    }
   ]
  },
  { "title": "Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 } },
  {
   "title": "Create space RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(api_createSpace_total[1m])"
    }
   ]
  },
  {
   "title": "Delete space RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 177 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(api_deleteSpace_total[1m])"
    }
   ]
  },
  {
   "title": "Get Space RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 186 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(api_getSpace_total[1m])" }
   ]
  }
 ]
}