global:
    scrape_interval: 10s
    scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    file_sd_configs:
      - files:
          - 'targets/*.json'