apiVersion: v1
kind: Service
metadata:
  name: monitoring
  labels:
    run: monitoring
spec:
  ports:
    - port: 9090
      protocol: TCP
      name: "prometheus"
    - port: 9095
      protocol: TCP
      name: "grafana"
  selector:
    run: monitoring
  type: "LoadBalancer"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
spec:
  selector:
    matchLabels:
      name: monitoring
      run: monitoring
  replicas: 1
  template:
    metadata:
      labels:
        name: monitoring
        run: monitoring
    spec:
      hostname: monitoring
      containers:
        - image: faderskd/easydb-monitoring
          name: monitoring-container
          ports:
            - containerPort: 9090
            - containerPort: 9095
          volumeMounts:
            - name: targets
              mountPath: /etc/prometheus/targets
      volumes:
        - name: targets

