apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  ports:
    - port: 8081
      protocol: TCP
      name: "load-balancer-api"
    - port: 8080
      protocol: TCP
      name: "http"
  selector:
    run: nginx
  type: "LoadBalancer"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      name: nginx
      run: nginx
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx
        run: nginx
    spec:
      hostname: nginx
      containers:
        - image: faderskd/easydb-load-balancer
          name: nginx-container
          ports:
            - containerPort: 8080
            - containerPort: 8081
