apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    run: zookeeper
spec:
  ports:
    - port: 2181
      protocol: TCP
  selector:
    run: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      name: zookeeper
      run: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
        run: zookeeper
    spec:
      hostname: zookeeper
      containers:
        - image: faderskd/easydb-zookeeper
          name: zookeeper-container
          ports:
            - containerPort: 2181
