version: "3"
services:
  discovery-scraper:
    build:
      context: ""
      dockerfile: DiscoveryScraper
    image: easydb/discovery_scraper
    depends_on:
      - zookeeper
      - nginx
    networks:
      - easydb

  nginx:
    build:
      context: ""
      dockerfile: Nginx
    image: easydb/load_balancer
    depends_on:
      - easydb
    networks:
      - easydb
    ports:
      - "8000:80"
      - "8001:8081"

  easydb:
    build:
      context: ""
      dockerfile: Easydb
    image: easydb/app
    depends_on:
      - monitoring
      - mongo
      - zookeeper
    networks:
      - easydb

  monitoring:
    build:
      context: ""
      dockerfile: Monitoring
    image: easydb/monitoring
    networks:
      - easydb
    ports:
      - "9090:9090"
      - "9095:9095"

  mongo:
    build:
      context: ""
      dockerfile: Mongo
    image: easydb/mongo
    volumes:
      - mongo-data-volume:/data/easydb/mongodb
    networks:
      - easydb

  zookeeper:
    build:
      context: ""
      dockerfile: Zookeeper
    image: easydb/zookeeper
    networks:
      - easydb
    ports:
      - "2181:2181"

volumes:
  mongo-data-volume:

networks:
  easydb: