version: "3"
services:
  easydb:
    build:
      context: ""
      dockerfile: Easydb
    image: easydb/app
    volumes:
      - log-volume:/var/log/easydb/
    depends_on:
      - monitoring
      - mongo
      - zookeeper
  monitoring:
    build:
      context: ""
      dockerfile: Monitoring
    image: easydb/monitoring
  mongo:
    build:
      context: ""
      dockerfile: Mongo
    image: easydb/mongo
    volumes:
      - log-volume:/var/log/easydb/
      - mongo-data-volume:/data/easydb/mongodb
  zookeeper:
    build:
      context: ""
      dockerfile: Zookeeper
    image: easydb/zookeeper
    volumes:
      - log-volume:/var/log/easydb

volumes:
  log-volume:
  mongo-data-volume: