# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "private_network", ip: "10.10.10.11"

  config.vm.synced_folder "../../", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
  end
  config.vm.provision "shell", path: "./scripts/init.sh"
  config.vm.provision "file", source: "./files/prometheus.pp", destination: "/home/vagrant/prometheus.pp"
  config.vm.provision "shell", path: "./scripts/provision_prometheus.sh"
end
