{
 "title": "easydb",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server 5xx RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_v1_requests_5xx_total[1m]))"
      }
     ]
    },
    {
     "title": "Server 4xx RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_v1_requests_4xx_total[1m]))"
      }
     ]
    },
    {
     "title": "Server 2xx RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_v1_requests_2xx_total[1m]))"
      }
     ]
    },
    {
     "title": "Server RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_v1_requests_all_total[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads alive",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_threads_live_threads" }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "system_cpu_usage" }
     ]
    },
    {
     "title": "JVM memory used",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"heap\"}"
      }
     ]
    },
    {
     "title": "CPU count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "system_cpu_count" }
     ]
    }
   ]
  },
  { "title": "Locker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Lock element RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(lockElement_total[1m]))"
    }
   ]
  },
  {
   "title": "Unlock element RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(unlockElement_total[1m]))"
    }
   ]
  },
  {
   "title": "Lock bucket RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(lockBucket_total[1m]))"
    }
   ]
  },
  {
   "title": "Unlock bucket RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(unlockBucket_total[1m]))"
    }
   ]
  },
  {
   "title": "Lock space RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(lockSpace_total[1m]))"
    }
   ]
  },
  {
   "title": "Unlock space RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(unlockSpace_total[1m]))"
    }
   ]
  },
  {
   "title": "Element locker errors RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(elementLockerErrors_total[1m]))"
    }
   ]
  },
  {
   "title": "Bucket locker errors RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(bucketLockerErrors_total[1m]))"
    }
   ]
  },
  {
   "title": "Space locker errors RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(spaceLockerErrors_total[1m]))"
    }
   ]
  },
  {
   "title": "Element locker Timeouts RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(elementLockerTimeouts_total[1m]))"
    }
   ]
  },
  {
   "title": "Bucket locker Timeouts RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(bucketLockerTimeouts_total[1m]))"
    }
   ]
  },
  {
   "title": "Space locker Timeouts RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(spaceLockerTimeouts_total[1m]))"
    }
   ]
  },
  {
   "title": "Element locking time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(elementLockingTime_seconds_bucket[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "Element unlocking time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(elementUnlockingTime_seconds_bucket[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "Bucket locking time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(bucketLockingTime_seconds_bucket[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "Bucket unlocking time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(bucketUnlockingTime_seconds_bucket[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "Space locking time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(spaceLockingTime_seconds_bucket[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "Space unlocking time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(spaceUnlockingTime_seconds_bucket[5m])) by (le)) "
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Begin transaction RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_beginTransaction_total[1m]))"
    }
   ]
  },
  {
   "title": "Commit transaction RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_commitTransaction_total[1m]))"
    }
   ]
  },
  {
   "title": "Add transaction operation RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(api_addTransactionOperation_total[1m])) by (instance, operation)"
    }
   ]
  },
  {
   "title": "Aborted transactions RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(abortedTransactions_total[1m]))"
    }
   ]
  },
  {
   "title": "Compound transaction time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(compoundTransactionTime_seconds_bucket[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "Single element transaction time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(singleElementTransactionTime_seconds_bucket[5m])) by (le)) "
    }
   ]
  },
  { "title": "Bucket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Delete Bucket RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_deleteBucket_total[1m]))"
    }
   ]
  },
  {
   "title": "Add Element RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_addElement_total[1m]))"
    }
   ]
  },
  {
   "title": "Update Element RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_updateElement_total[1m]))"
    }
   ]
  },
  {
   "title": "Get Element RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_getElement_total[1m]))"
    }
   ]
  },
  {
   "title": "Delete Element RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_deleteElement_total[1m]))"
    }
   ]
  },
  {
   "title": "Filter Elements RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(api_filterElements_total[1m]))"
    }
   ]
  },
  { "title": "Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 } },
  {
   "title": "Create space RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(api_createSpace_total[1m])"
    }
   ]
  },
  {
   "title": "Delete space RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 141 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(api_deleteSpace_total[1m])"
    }
   ]
  },
  {
   "title": "Get Space RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(api_getSpace_total[1m])" }
   ]
  }
 ]
}