apiVersion: v1
kind: Service
metadata:
  name: mongo-SHARDX
  labels:
    run: mongo-SHARDX
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    run: mongo-SHARDX
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-SHARDX
spec:
  selector:
    matchLabels:
      run: mongo-SHARDX # has to match .spec.template.metadata.labels
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo-SHARDX
        run: mongo-SHARDX
    spec:
      hostname: mongo-SHARDX
      containers:
        - image: faderskd/easydb-mongo
          name: mongodb-shard-CONTAINERX
          ports:
            - containerPort: 27017
          command:
            - "mongod"
            - "--port"
            - "27017"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "mongo-replicaset"
            - "--dbpath"
            - "/data/db"
          volumeMounts:
            - name: mongo-SHARDX-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-SHARDX-persistent-storage