apiVersion: v1
kind: Service
metadata:
  name: mongo-config-SERVERX
  labels:
    run: mongo-config-SERVERX
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    run: mongo-config-SERVERX
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-config-SERVERX
spec:
  selector:
    matchLabels:
      run: mongo-config-SERVERX # has to match .spec.template.metadata.labels
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo-config-SERVERX
        run: mongo-config-SERVERX
    spec:
      hostname: mongo-config-SERVERX
      containers:
        - image: faderskd/easydb-mongo
          name: mongo-config-SERVERX
          ports:
             - containerPort: 27017
          command:
            - "mongod"
            - "--configsvr"
            - "--port"
            - "27017"
            - "--dbpath"
            - "/data/db"
            - "--bind_ip_all"
            - "--replSet"
            - "mongo-config-server"
          volumeMounts:
            - name: mongodb-config-SERVERX-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-config-SERVERX-persistent-storage
          persistentVolumeClaim:
            claimName: local-storage-CLAIMX