kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-storage-CLAIMX
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
