version: "3.3"
services:
  discovery-scraper:
    build:
      context: ""
      dockerfile: Dockerfile.discoveryscraper
    image: "easydb/discovery_scraper:$TAG"

  nginx:
    build:
      context: ""
      dockerfile: Dockerfile.nginx
    image: "easydb/load_balancer:$TAG"

  easydb:
    build:
      context: ""
      dockerfile: Dockerfile.easydb
    image: "easydb/app:$TAG"

  monitoring:
    build:
      context: ""
      dockerfile: Dockerfile.monitoring
    image: "easydb/monitoring:$TAG"

  zookeeper:
    build:
      context: ""
      dockerfile: Dockerfile.zookeeper
    image: "easydb/zookeeper:$TAG"

  testcontainer:
    build:
      context: ""
      dockerfile: Dockerfile.testcontainer
    image: "easydb/testcontainer:$TAG"

  mongo:
    build:
      context: ""
      dockerfile: Dockerfile.mongo
    image: "easydb/mongo:$TAG"