FROM ubuntu:18.04

ENV ZOOKEEPER_VERSION 3.5.5
ENV JAVA_HOME "/usr/lib/jvm/java-8-openjdk-amd64"

    # install java8
RUN apt-get -y update && \
    apt-get -y install software-properties-common && \
    add-apt-repository ppa:openjdk-r/ppa 2>/dev/null && \
    apt-get -y update && \
    apt-get -y install openjdk-8-jdk

# install zookeeper
RUN apt-get install -y wget && \
    wget https://www-eu.apache.org/dist/zookeeper/zookeeper-${ZOOKEEPER_VERSION}/apache-zookeeper-${ZOOKEEPER_VERSION}-bin.tar.gz && \
    tar -xf apache-zookeeper-${ZOOKEEPER_VERSION}-bin.tar.gz -C /opt/ && \
    mv /opt/apache-zookeeper-${ZOOKEEPER_VERSION}-bin /opt/zookeeper && \
    rm apache-zookeeper-${ZOOKEEPER_VERSION}-bin.tar.gz

ADD files/zookeeper.cfg /opt/zookeeper/conf/zookeeper.cfg

EXPOSE 2181

CMD /bin/bash /opt/zookeeper/bin/zkServer.sh start-foreground /opt/zookeeper/conf/zookeeper.cfg