spring:
  application:
    name: easydb
  metrics:
    prometheus:
      enabled: true

management:
  security:
    enabled: false

  endpoints:
    web:
      exposure:
        include: '*'

mongo:
  databaseName: easydb
  host: localhost
  port: 27017
  username: easydb
  password: 123456
