{
 "title": "easydb",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Locker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lock element RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(lockElement_total[1m]))"
      }
     ]
    },
    {
     "title": "Lock element RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(lockElement_total[1m]))"
      }
     ]
    },
    {
     "title": "Locker errors RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(lockerErrors_total[1m]))"
      }
     ]
    },
    {
     "title": "Locker Timeouts RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(lockerTimeouts_total[1m]))"
      }
     ]
    },
    {
     "title": "Element locking time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(lockingTime_seconds_max[1m])) by (instance)"
      }
     ]
    },
    {
     "title": "Element unlocking time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(unlockingTime_seconds_max[1m])) by (instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Begin transaction RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_beginTransaction_total[1m]))"
      }
     ]
    },
    {
     "title": "Commit transaction RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_commitTransaction_total[1m]))"
      }
     ]
    },
    {
     "title": "Add transaction operation RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_addTransactionOperation_total[1m])) by (instance, operation)"
      }
     ]
    },
    {
     "title": "Aborted transactions RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(abortedTransactions_total[1m]))"
      }
     ]
    },
    {
     "title": "Compound transaction time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(compoundTransactionTime_seconds_max[1m])) by (instance)"
      }
     ]
    },
    {
     "title": "Single element transaction time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(singleElementTransactionTime_seconds_max[1m])) by (instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "Bucket",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delete Bucket RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_deleteBucket_total[1m]))"
      }
     ]
    },
    {
     "title": "Add Element RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_addElement_total[1m]))"
      }
     ]
    },
    {
     "title": "Update Element RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_updateElement_total[1m]))"
      }
     ]
    },
    {
     "title": "Get Element RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_getElement_total[1m]))"
      }
     ]
    },
    {
     "title": "Delete Element RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_deleteElement_total[1m]))"
      }
     ]
    },
    {
     "title": "Filter Elements RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_filterElements_total[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Create space RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(api_createSpace_total[1m])"
      }
     ]
    },
    {
     "title": "Delete space RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(api_deleteSpace_total[1m])"
      }
     ]
    },
    {
     "title": "Get Space RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "rate(api_getSpace_total[1m])" }
     ]
    }
   ]
  }
 ]
}