{
 "title": "easydb",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(http_server_requests_seconds_max{status=\"500\"}[1m]))"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Server RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(http_server_requests_seconds_max[1m])) "
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "Threads alive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_live" }
   ]
  },
  {
   "title": "CPU count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_count" }
   ]
  },
  {
   "title": "JVM memory used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}"
    }
   ]
  },
  {
   "title": "Locker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lock element",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(lockElement_total[1m]))"
      }
     ]
    },
    {
     "title": "Unlock element",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(unlockElement_total[1m]))"
      }
     ]
    },
    {
     "title": "Lock bucket",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(lockBucket_total[1m]))"
      }
     ]
    },
    {
     "title": "Unlock bucket",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(lockBucket_total[1m]))"
      }
     ]
    },
    {
     "title": "Lock space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(lockSpace_total[1m]))"
      }
     ]
    },
    {
     "title": "Unlock space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(unlockSpace_total[1m]))"
      }
     ]
    },
    {
     "title": "Element locker errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(elementLockerErrors_total[1m]))"
      }
     ]
    },
    {
     "title": "Bucket locker errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(bucketLockerErrors_total[1m]))"
      }
     ]
    },
    {
     "title": "Space locker errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(spaceLockerErrors_total[1m]))"
      }
     ]
    },
    {
     "title": "Element locker Timeouts",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(elementLockerTimeouts_total[1m]))"
      }
     ]
    },
    {
     "title": "Bucket locker Timeouts",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(bucketLockerTimeouts_total[1m]))"
      }
     ]
    },
    {
     "title": "Space locker Timeouts",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(spaceLockerTimeouts_total[1m]))"
      }
     ]
    },
    {
     "title": "Element locking time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(elementLockingTime_seconds_max[1m])) by (instance)"
      }
     ]
    },
    {
     "title": "Element unlocking time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(elementUnlockingTime_seconds_max[1m])) by (instance)"
      }
     ]
    },
    {
     "title": "Bucket locking time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(bucketLockingTime_seconds_max[1m])) by (instance)"
      }
     ]
    },
    {
     "title": "Bucket unlocking time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(bucketUnlockingTime_seconds_max[1m])) by (instance)"
      }
     ]
    },
    {
     "title": "Space locking time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(spaceLockingTime_seconds_max[1m])) by (instance)"
      }
     ]
    },
    {
     "title": "Space unlocking time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(spaceUnlockingTime_seconds_max[1m])) by (instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Begin transaction RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_beginTransaction_total[1m]))"
      }
     ]
    },
    {
     "title": "Commit transaction RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_commitTransaction_total[1m]))"
      }
     ]
    },
    {
     "title": "Add transaction operation RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_addTransactionOperation_total[1m])) by (instance, operation)"
      }
     ]
    },
    {
     "title": "Aborted transactions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(abortedTransactions_total[1m]))"
      }
     ]
    },
    {
     "title": "Compound transaction time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(compoundTransactionTime_seconds_max[1m])) by (instance)"
      }
     ]
    },
    {
     "title": "Single element transaction time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(singleElementTransactionTime_seconds_max[1m])) by (instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "Bucket",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delete Bucket RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_deleteBucket_total[1m]))"
      }
     ]
    },
    {
     "title": "Add Element RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_addElement_total[1m]))"
      }
     ]
    },
    {
     "title": "Update Element RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_updateElement_total[1m]))"
      }
     ]
    },
    {
     "title": "Get Element RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_getElement_total[1m]))"
      }
     ]
    },
    {
     "title": "Delete Element RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_deleteElement_total[1m]))"
      }
     ]
    },
    {
     "title": "Filter Elements RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(api_filterElements_total[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Create space RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(api_createSpace_total[1m])"
      }
     ]
    },
    {
     "title": "Delete space RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(api_deleteSpace_total[1m])"
      }
     ]
    },
    {
     "title": "Get Space RPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "rate(api_getSpace_total[1m])" }
     ]
    }
   ]
  }
 ]
}